// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"context"
)

type Querier interface {
	GetUser(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
