// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/anhnmt/golang-clean-architecture/internal/user/delivery/rpc"
	"github.com/anhnmt/golang-clean-architecture/internal/user/usecase"
	"github.com/anhnmt/golang-clean-architecture/pkg/config"
	"github.com/anhnmt/golang-clean-architecture/pkg/postgres"
	"google.golang.org/grpc"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func NewServerEngine(cfg config.Server, pg postgres.DBEngine, grpcServer *grpc.Server) Server {
	useCase := usecase.New(pg)
	userServiceServer := rpc.New(grpcServer, useCase)
	serverServer := New(cfg, pg, grpcServer, userServiceServer)
	return serverServer
}
